### ISSUE TITLE
An consultation on Deformable Transformer Block!!!

### ISSUE THREAD

**Issue by Starboy-at-earth** [RobertLuo1/NeurIPS2023_SOC#4]
Dear author:
       Thank you for your great contributions to the community. I am currently learning your code. However, some problems haunt me in reading. Could you please tell me if Deformable Transformer blocks, including encoder and decoder, support AMP in pytorch? Speeding up, even to a little extent, in VOS task is important. Thank you in advance!

**Comment by RobertLuo1** [comment]
Thanks for your attention to our work.
We directly use the Deformable Detr from their official github repository https://github.com/fundamentalvision/Deformable-DETR. 
Maybe you can check if they can be applied with AMP in their official repo?

**Comment by Starboy-at-earth** [comment]
@RobertLuo1 No modification found from the original source! Thank you very much!
