### ISSUE TITLE
A2D dataset trian for scratch

### ISSUE THREAD

**Issue by wangyihanwyh** [RobertLuo1/NeurIPS2023_SOC#5]
Dear author:
Thank you for your great contributions to the community. I am currently learning your code. However, some problems haunt me in reading. I am unable to reproduce the effect of train for scratch on the a2d dataset in your paper. Could you please help me check if there are any errors in the parameter settings or if there are any other issues.
[configa2dtrainforscratch.txt](https://github.com/RobertLuo1/NeurIPS2023_SOC/files/14548748/configa2dtrainforscratch.txt)
[loga2dtrainforscratch.txt](https://github.com/RobertLuo1/NeurIPS2023_SOC/files/14548750/loga2dtrainforscratch.txt)

**Comment by RobertLuo1** [comment]
Thanks for your attention to our work!
We have checked your config and find that the lr for A2D from scratch is wrong. It should be 5e-5 and 5e-6. Thanks for your notification!
