### ISSUE TITLE
[MMF] Why implement t->v and v->t with video features from different layer?

### ISSUE THREAD

**Issue by wjun0830** [RobertLuo1/NeurIPS2023_SOC#6]
Hello Robert!

Can you explain why you implemented text-to-video cross-attention with video features from the last visual layer whereas the video-to-text cross-attention layer is performed with the one from the second last layer?

Does the performance decreases if performing video-to-text cross-attention with the last layer visual features?

Thanks in advance.

**Comment by RobertLuo1** [comment]
Thanks for your interest on our work!
For the T2V part, we refer to the previous work [Referformer](https://github.com/wjn922/ReferFormer). As for V2T, we think that the last visual feature with the lowest resolution is encoded the highest level semantics and it may be not quite suitable for V2T where the text feature may need relatively more fine-grained visual feauture for calibration. However, we have not tested it with experiments.

**Comment by wjun0830** [comment]
Thanks for your response I get it
