### ISSUE TITLE
why not use query's padding_mask  in vision language early-fusion

### ISSUE THREAD

**Issue by tmliang** [RobertLuo1/NeurIPS2023_SOC#7]
Hi, thanks for your work! I am a bit confused about the reason for disabling the tgt_padding_mask in the following part.

https://github.com/RobertLuo1/NeurIPS2023_SOC/blob/3a4997104fffa2b89c17f2b8598a87a9e715763c/models/soc.py#L235-L248

**Comment by RobertLuo1** [comment]
Thanks for your interest on our work!
In our early experiment, we found that it performed better. The reason behind is that we think the visual feature contains large proportion of unreleated contents and here we would like to use the highlight regions to update the text embedding. Maybe the padding from text embedding serves as the dummy token to help distribute the attention weight from background features.

**Comment by tmliang** [comment]
Thanks! It is insightful!
